// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWs2WZ81L4pJoJIEa1-mxtt3Ykl5BBOvo',
    appId: '1:560781649721:web:6d096d395c2052941deae8',
    messagingSenderId: '560781649721',
    projectId: 'marketplace-63a0b',
    authDomain: 'marketplace-63a0b.firebaseapp.com',
    storageBucket: 'marketplace-63a0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc0d7vFVb1PCc8LMFxNfcZpcAz6BZMRg4',
    appId: '1:560781649721:android:57261439d4b29ac01deae8',
    messagingSenderId: '560781649721',
    projectId: 'marketplace-63a0b',
    storageBucket: 'marketplace-63a0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQHhYIXBKMDb-kZjLMgCdQeghtemdV4k',
    appId: '1:560781649721:ios:29947b7e3c9d5e0b1deae8',
    messagingSenderId: '560781649721',
    projectId: 'marketplace-63a0b',
    storageBucket: 'marketplace-63a0b.appspot.com',
    iosBundleId: 'com.example.droneMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQHhYIXBKMDb-kZjLMgCdQeghtemdV4k',
    appId: '1:560781649721:ios:29947b7e3c9d5e0b1deae8',
    messagingSenderId: '560781649721',
    projectId: 'marketplace-63a0b',
    storageBucket: 'marketplace-63a0b.appspot.com',
    iosBundleId: 'com.example.droneMarket',
  );
}
